config/routes.rb
Rails.application.routes.draw do
  #resources :restaurants do
   #lister several restaurants
   #collection do
    #get :top
  #end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # routes pour 1 restaurant = 1 member
  #member do
   # get :chef # /restaurants/:id/chef
  #end
  #end
  #

  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end

    # on veut une review
    #  GET /restaurant/:restaurant_id/reviews/new -> #new
    #  POST /restaurant/:restaurant_id/reviews -> #create
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy


  def reviews
    Review.where(restaurant_id: self.id)
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[ show edit update destroy, :chef]

  # GET /restaurants/top les 5étoiles
  def top
    @restaurants = Restaurant.where(stars: 5)
    #ca va render top.html.erb
  end


 #method Chef
 #GET /restaurants/:id/chef
 #On veut récuper le chef's name
 def chef
    @restaurant = Restaurant.find(params[:id])
    @chef_name = @restaurant.chef_name
  end

  # GET /restaurants or /restaurants.json
  def index
    @restaurants = Restaurant.all
    #index.html.erb
  end

  # GET /restaurants/1 or /restaurants/1.json
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants or /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: "Restaurant was successfully created." }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1 or /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: "Restaurant was successfully updated." }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1 or /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: "Restaurant was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :stars)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

   # GET /restaurants/:restaurant_id/reviews/new
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
    # review/new.html.erb
  end


# POST /restaurants/:restaurant_id/reviews
  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    #review.restaurant.id = @restaurant.id
    @review.restaurant = @restaurant
    @review.save
    #rediriger :
    redirect_to restaurant_path(@restaurant)
  end


private

  def review_params
    params.require(:review).permit(:content)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RestaurantReviews</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :stars %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/restaurants/chef.html.erb
<h1><%= @chef_name %></h1>


<iframe src="https://giphy.com/embed/583D8jvar65CMoETxU" width="480" height="266" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/bbc-royal-wedding-royalwedding-583D8jvar65CMoETxU"></a></p>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Restaurants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Stars</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.address %></td>
        <td><%= restaurant.stars %></td>
        <td><%= link_to 'Show', restaurant %></td>
        <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
        <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-6 offset-3">

      <p id="notice"><%= notice %></p>

      <p>
        <strong>Name:</strong>
        <%= @restaurant.name %>
      </p>

      <p>
        <strong>Address:</strong>
        <%= @restaurant.address %>
      </p>

      <p>
        <strong>Stars:</strong>
        <%= @restaurant.stars %>
      </p>

      <h5>Reviews</h5>
      <ul class="list-group">
        <% @restaurant.reviews.each do |review|%>


      </ul>


      <%#= link_to 'Who is the chef', chef_restaurant_path(@restaurant) %>

      <br>

      <%= link_to 'Edit', edit_restaurant_path(@restaurant) %>
      <%= link_to 'Back', restaurants_path %>



    </div>
  </div>
</div>

app/views/restaurants/top.html.erb
<p id="notice"><%= notice %></p>

<h1>Restaurants - 5 étoiles </h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Stars</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.address %></td>
        <td><%= restaurant.stars %></td>
        <td><%= link_to 'Show', restaurant %></td>
        <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
        <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Restaurant', new_restaurant_path %>

app/views/reviews/new.html.erb
<h1>REVIEW</h1>

<div class="container">
  <div class="row">
    <div class="col-6 offset-3">
      <h1> Add Review for <%= @restaurant.name %></h1>
      <%= simple_form_for([@restaurant, @review]) do |f| %>
      <%= f.input :content %>
      <%= f.submit "Submit review" %>
    <% end %>

    </div>
  </div>
</div>


<!---- Review.new
  POST /review -> reviews_path -->
<!---- POST /restaurants/42/reviews/new -->